name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: npm install, build, and test
      run: |
        make install
        make start
        make lint
        env:
          CI: true
